package:
  name: scarab
  version: 1.0.0
source:
  git_url: https://github.com/hallamlab/SCARAB.git
  git_rev: v1.0.0
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
requirements:
  host:
    - python 3.10
    - pip
    - setuptools >=68,<81
    - wheel
  run:
    - python >=3.10,<3.11
    - numpy 1.24.4
    - pandas 2.0.3
    - scikit-learn 1.3.0
    - umap-learn 0.5.3
    - hdbscan 0.8.30
    - sourmash 4.8.2
    - pyfastx 1.1.0
    - scikit-bio 0.5.8
    - tqdm
    - numba 0.57.1
    - scipy 1.11.1
    - screed 1.1.2
    - six 1.16.0
    - setuptools>=68,<81
    - minimap2 2.26
    - samtools 1.16.1
    - metabat2 2.15
    - bbmap 39.01
    - seqkit 2.4.0
test:
  imports:
    - scarab.commands
    - scarab.utilities
    - scarab.clusterer
  commands:
    - scarab info
    - scarab recruit --help
    - minimap2 --version
    - samtools --version
    - command -v jgi_summarize_bam_contig_depths
    - command -v dedupe.sh
about:
  home: https://github.com/hallamlab/SCARAB
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Genome-guided recruitment of metagenomic contigs and extended partial genomes.
extra:
  recipe-maintainers:
    - RyloByte
